### ISSUE TITLE
Поддержка статистики энергии

### ISSUE THREAD

**Issue by afomichev** [slacky1965/watermeter_zed#33]
Не смотря на единицы измерения L не видит статистики
![image](https://github.com/user-attachments/assets/433acdeb-1656-457e-9ec6-43da457e03dc)
при этом от ватериуса прекрасно заходит в кубах

**Comment by alekslegkih** [comment]
Добавьте в файл configuration.yaml

homeassistant:
  customize:
    sensor.water_cold:
      unit_of_measurement: m³
      device_class: water
      state_class: total

Для отображения в панели Энергия, нужны эти параметры.

**Comment by afomichev** [comment]
Спасибо! работает! 
а конвертор не может сразу отдавать с такими типами?

**Comment by DisloyalSnow911** [comment]
> Добавьте в файл configuration.yaml
> 
> homeassistant: customize: sensor.water_cold: unit_of_measurement: m³ device_class: water state_class: total
> 
> Для отображения в панели Энергия, нужны эти параметры.

Подскажите, а почему без customize он не видит датчики?

**Comment by locosmo** [comment]
> Добавьте в файл configuration.yaml
> 
> homeassistant: customize: sensor.water_cold: unit_of_measurement: m³ device_class: water state_class: total
> 
> Для отображения в панели Энергия, нужны эти параметры.

Добавил, но источник воды не появился

![Image](https://github.com/user-attachments/assets/cd6fde20-b384-42e9-8755-b70ab150de5b)

![Image](https://github.com/user-attachments/assets/a0168931-c981-43e0-bc94-52d0e2d6c8d9)

В чем может быть дело?
sensor.water_cold - это какое-то предопределенное значение?

HA
Core: 2025.5.2
Supervisor: 2025.05.1

**Comment by alekslegkih** [comment]
> 
> В чем может быть дело? sensor.water_cold - это какое-то предопределенное значение?
> 

Это название вашего датчика.
```
homeassistant:
  customize:
    "sensor.watermeter_volume_1":
      friendly_name: "Горячая вода. Литры"
      icon: mdi:counter
      unit_of_measurement: L
      device_class: water
      state_class: total
    "sensor.watermeter_volume_2":
      friendly_name: "Холодная вода. Литры"
      icon: mdi:counter
      unit_of_measurement: L
      device_class: water
      state_class: total
```
